name: build-extension
run-name: Build Ariadne

# Only build on pushes to main
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build extension (Manifest V2)
        run: npm run package
      - name: Build extension (Manifest V3)
        run: npm run package:v3
      - name: Upload artifacts
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "web-ext-artifacts/*.zip"
          tags: true
        if: github.event_name != 'pull_request'
