name: chromium-build
run-name: Build Ariadne for Chromium-based browsers

# Only build on pushes to main
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build extension
        run: npm run build
      - name: Upload extension
        uses: actions/upload-artifact@v2
        with:
          name: ariadne-chromium
          path: release.zip
        if: github.event_name != 'pull_request'
